### ISSUE TITLE
getFirmware no funciona correctamente

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/PyTempico#1]
(v1.0)
@JoanAmaya encuentra que el método getFirmware() de la clase TempicoDevice no retorna respuesta.

Identifico que esto sucede por cómo está implementado el método. Si no se ha hecho llamado de getIdn previamente, el atributo firmware es vacío. 

Posible solución: implementar método getFirmware() similar a como está implementado el método getIdn(). Es decir, validar si está conectado, y si atributo firmware es vacío, entonces:
`self.readIdnFromDevice()`

**Comment by JoanAmaya** [comment]
Se ha actualizado la solución del problema en RamaTest2. La solución fue llevar a cabo exactamente la misma escritura del método getIdn pero para el parámetro de firmware con el fin de hacer el llamado al dispositivo a través del mensaje.

**Comment by daguzman35** [comment]
Función getFirmware() en core.py, de RamaTest2 en GitHub no ha cambiado. Asegurarse de sincronizar los cambios en GitHub.

**Comment by daguzman35** [comment]
Solucionado en rama main con 256bf6d889910e1b5e983d8ad4ae841181fa8e20
